<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>PAMS.Application</AssemblyName>
    <RootNamespace>PAMS.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PAMS.Domain\PAMS.Domain.csproj" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
  </ItemGroup>

</Project>
