// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PAMS.Infrastructure.Persistence;

#nullable disable

namespace PAMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PamsDbContext))]
    [Migration("20260303000000_AddProjectRoleToAllocation")]
    partial class AddProjectRoleToAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pams")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PAMS.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("accounts", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AllocatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<short>("Percentage")
                        .HasColumnType("smallint")
                        .HasColumnName("percentage");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectRole")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("project_role");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AllocatedById");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_alloc_employee_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_alloc_project")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("EmployeeId", "FromDate", "ToDate")
                        .HasDatabaseName("idx_alloc_employee_dates")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("allocations", "pams", t =>
                        {
                            t.HasCheckConstraint("chk_allocation_dates", "to_date IS NULL OR to_date >= from_date");

                            t.HasCheckConstraint("chk_allocation_percentage", "percentage BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("PAMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("idx_auditlog_actor");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_auditlog_created");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_auditlog_entity");

                    b.ToTable("audit_logs", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emp_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("ReportsToId")
                        .HasColumnType("uuid")
                        .HasColumnName("reports_to");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpCode")
                        .IsUnique();

                    b.HasIndex("ReportsToId")
                        .HasFilter("reports_to IS NOT NULL");

                    b.ToTable("employees", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.EmployeeSkill", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("EmployeeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("employee_skills", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("Billable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("billable");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_code");

                    b.Property<Guid?>("ProjectManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_manager_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Upcoming")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("projects", "pams", t =>
                        {
                            t.HasCheckConstraint("chk_project_dates", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("PAMS.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reportee_id");

                    b.Property<Guid>("TeamLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_lead_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_ptm_project");

                    b.HasIndex("ReporteeId")
                        .HasDatabaseName("idx_ptm_reportee");

                    b.HasIndex("TeamLeadId")
                        .HasDatabaseName("idx_ptm_team_lead");

                    b.HasIndex("ProjectId", "TeamLeadId", "ReporteeId")
                        .IsUnique()
                        .HasDatabaseName("uq_ptm_project_lead_reportee");

                    b.ToTable("project_team_members", "pams", t =>
                        {
                            t.HasCheckConstraint("chk_ptm_lead_not_reportee", "team_lead_id != reportee_id");
                        });
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("skills", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("config_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AllocationIncrement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("allocation_increment");

                    b.Property<int>("MinAllocationPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25)
                        .HasColumnName("min_allocation_pct");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("system_configs", "pams");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Allocation", b =>
                {
                    b.HasOne("PAMS.Domain.Entities.Employee", "AllocatedBy")
                        .WithMany()
                        .HasForeignKey("AllocatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Employee", "Employee")
                        .WithMany("Allocations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocatedBy");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PAMS.Domain.Entities.Employee", "ReportsTo")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportsToId");

                    b.Navigation("ReportsTo");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.EmployeeSkill", b =>
                {
                    b.HasOne("PAMS.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Project", b =>
                {
                    b.HasOne("PAMS.Domain.Entities.Account", "Account")
                        .WithMany("Projects")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Employee", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId");

                    b.Navigation("Account");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.HasOne("PAMS.Domain.Entities.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Employee", "Reportee")
                        .WithMany()
                        .HasForeignKey("ReporteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAMS.Domain.Entities.Employee", "TeamLead")
                        .WithMany()
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Reportee");

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Account", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("DirectReports");

                    b.Navigation("EmployeeSkills");

                    b.Navigation("ManagedProjects");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("PAMS.Domain.Entities.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
